version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:52"
      timezone: "Asia/Tokyo"
    allow:
      - dependency-type: "direct"
